A = int(input())
B = int(input())
C = int(input())
D = int(input())
diff1 = abs((A + B) - (C + D))
diff2 = abs((A + C) - (B + D))
diff3 = abs((A + D) - (B + C))
menor_diferenca = min(diff1, diff2, diff3)
print(menor_diferenca)